const COUNTRY_NAMES: Record<string, string> = {
  'Afghanistan':                      'Afeganistão',
  'Albania':                          'Albânia',
  'Algeria':                          'Argélia',
  'Andorra':                          'Andorra',
  'Angola':                           'Angola',
  'Antigua and Barbuda':              'Antígua e Barbuda',
  'Argentina':                        'Argentina',
  'Armenia':                          'Armênia',
  'Australia':                        'Austrália',
  'Austria':                          'Áustria',
  'Azerbaijan':                       'Azerbaijão',

  'Bahamas':                          'Bahamas',
  'Bahrain':                          'Bahrein',
  'Bangladesh':                       'Bangladesh',
  'Barbados':                         'Barbados',
  'Belarus':                          'Bielorrússia',
  'Belgium':                          'Bélgica',
  'Belize':                           'Belize',
  'Benin':                            'Benin',
  'Bhutan':                           'Butão',
  'Bolivia':                          'Bolívia',
  'Bosnia and Herzegovina':           'Bósnia e Herzegovina',
  'Botswana':                         'Botsuana',
  'Brazil':                           'Brasil',
  'Brunei':                           'Brunei',
  'Bulgaria':                         'Bulgária',
  'Burkina Faso':                     'Burkina Faso',
  'Burundi':                          'Burundi',

  'Cambodia':                         'Camboja',
  'Cameroon':                         'Camarões',
  'Canada':                           'Canadá',
  'Cape Verde':                       'Cabo Verde',
  'Central African Republic':         'República Centro-Africana',
  'Chad':                             'Chade',
  'Chile':                            'Chile',
  'China':                            'China',
  'Colombia':                         'Colômbia',
  'Comoros':                          'Comores',
  'Congo DR':                            'Congo',
  'Costa Rica':                       'Costa Rica',
  'Croatia':                          'Croácia',
  'Cuba':                             'Cuba',
  'Curaçao':                          'Curaçau',
  'Cyprus':                           'Chipre',
  'Czechia':                          'República Tcheca',
  'Czech Republic':                   'República Tcheca',

  'Democratic Republic of the Congo': 'República Democrática do Congo',
  'Denmark':                          'Dinamarca',
  'Djibouti':                         'Djibuti',
  'Dominica':                         'Dominica',
  'Dominican Republic':               'República Dominicana',

  'Ecuador':                          'Equador',
  'Egypt':                            'Egito',
  'El Salvador':                      'El Salvador',
  'England':                          'Inglaterra',
  'Equatorial Guinea':                'Guiné Equatorial',
  'Eritrea':                          'Eritreia',
  'Estonia':                          'Estônia',
  'Eswatini':                         'Essuatíni',
  'Ethiopia':                         'Etiópia',

  'Fiji':                             'Fiji',
  'Finland':                          'Finlândia',
  'France':                           'França',

  'Gabon':                            'Gabão',
  'Gambia':                           'Gâmbia',
  'Georgia':                          'Geórgia',
  'Germany':                          'Alemanha',
  'Ghana':                            'Gana',
  'Greece':                           'Grécia',
  'Grenada':                          'Granada',
  'Guatemala':                        'Guatemala',
  'Guinea':                           'Guiné',
  'Guinea-Bissau':                    'Guiné-Bissau',
  'Guyana':                           'Guiana',

  'Haiti':                            'Haiti',
  'Honduras':                         'Honduras',
  'Hungary':                          'Hungria',

  'Iceland':                          'Islândia',
  'India':                            'Índia',
  'Indonesia':                        'Indonésia',
  'Iran':                             'Irã',
  'Iraq':                             'Iraque',
  'Ireland':                          'Irlanda',
  'Israel':                           'Israel',
  'Italy':                            'Itália',
  'Ivory Coast':                      'Costa do Marfim',
  "Côte d'Ivoire":                    'Costa do Marfim',

  'Jamaica':                          'Jamaica',
  'Japan':                            'Japão',
  'Jordan':                           'Jordânia',

  'Kazakhstan':                       'Cazaquistão',
  'Kenya':                            'Quênia',
  'Kiribati':                         'Quiribati',
  'Kosovo':                           'Kosovo',
  'Kuwait':                           'Kuwait',
  'Kyrgyzstan':                       'Quirguistão',

  'Laos':                             'Laos',
  'Latvia':                           'Letônia',
  'Lebanon':                          'Líbano',
  'Lesotho':                          'Lesoto',
  'Liberia':                          'Libéria',
  'Libya':                            'Líbia',
  'Liechtenstein':                    'Liechtenstein',
  'Lithuania':                        'Lituânia',
  'Luxembourg':                       'Luxemburgo',

  'Madagascar':                       'Madagáscar',
  'Malawi':                           'Malawi',
  'Malaysia':                         'Malásia',
  'Maldives':                         'Maldivas',
  'Mali':                             'Mali',
  'Malta':                            'Malta',
  'Marshall Islands':                 'Ilhas Marshall',
  'Mauritania':                       'Mauritânia',
  'Mauritius':                        'Maurício',
  'Mexico':                           'México',
  'Micronesia':                       'Micronésia',
  'Moldova':                          'Moldávia',
  'Monaco':                           'Mônaco',
  'Mongolia':                         'Mongólia',
  'Montenegro':                       'Montenegro',
  'Morocco':                          'Marrocos',
  'Mozambique':                       'Moçambique',
  'Myanmar':                          'Mianmar',

  'Namibia':                          'Namíbia',
  'Nauru':                            'Nauru',
  'Nepal':                            'Nepal',
  'Netherlands':                      'Holanda',
  'New Zealand':                      'Nova Zelândia',
  'Nicaragua':                        'Nicarágua',
  'Niger':                            'Níger',
  'Nigeria':                          'Nigéria',
  'North Korea':                      'Coreia do Norte',
  'North Macedonia':                  'Macedônia do Norte',
  'Northern Ireland':                 'Irlanda do Norte',
  'Norway':                           'Noruega',

  'Oman':                             'Omã',

  'Pakistan':                         'Paquistão',
  'Palau':                            'Palau',
  'Panama':                           'Panamá',
  'Papua New Guinea':                 'Papua Nova Guiné',
  'Paraguay':                         'Paraguai',
  'Peru':                             'Peru',
  'Philippines':                      'Filipinas',
  'Poland':                           'Polônia',
  'Portugal':                         'Portugal',

  'Qatar':                            'Catar',

  'Romania':                          'Romênia',
  'Russia':                           'Rússia',
  'Rwanda':                           'Ruanda',

  'Saint Kitts and Nevis':            'São Cristóvão e Névis',
  'Saint Lucia':                      'Santa Lúcia',
  'Saint Vincent and the Grenadines': 'São Vicente e Granadinas',
  'Samoa':                            'Samoa',
  'San Marino':                       'San Marino',
  'Sao Tome and Principe':            'São Tomé e Príncipe',
  'Saudi Arabia':                     'Arábia Saudita',
  'Scotland':                         'Escócia',
  'Senegal':                          'Senegal',
  'Serbia':                           'Sérvia',
  'Seychelles':                       'Seicheles',
  'Sierra Leone':                     'Serra Leoa',
  'Singapore':                        'Cingapura',
  'Slovakia':                         'Eslováquia',
  'Slovenia':                         'Eslovênia',
  'Solomon Islands':                  'Ilhas Salomão',
  'Somalia':                          'Somália',
  'South Africa':                     'África do Sul',
  'Korea Republic':                      'Coreia do Sul',
  'South Sudan':                      'Sudão do Sul',
  'Spain':                            'Espanha',
  'Sri Lanka':                        'Sri Lanka',
  'Sudan':                            'Sudão',
  'Suriname':                         'Suriname',
  'Sweden':                           'Suécia',
  'Switzerland':                      'Suíça',
  'Syria':                            'Síria',

  'Taiwan':                           'Taiwan',
  'Tajikistan':                       'Tajiquistão',
  'Tanzania':                         'Tanzânia',
  'Thailand':                         'Tailândia',
  'Timor-Leste':                      'Timor-Leste',
  'Togo':                             'Togo',
  'Tonga':                            'Tonga',
  'Trinidad and Tobago':              'Trinidad e Tobago',
  'Tunisia':                          'Tunísia',
  'Turkey':                           'Turquia',
  'Türkiye':                          'Turquia',
  'Turkmenistan':                     'Turcomenistão',
  'Tuvalu':                           'Tuvalu',

  'Uganda':                           'Uganda',
  'Ukraine':                          'Ucrânia',
  'United Arab Emirates':             'Emirados Árabes Unidos',
  'United Kingdom':                   'Reino Unido',
  'United States':                    'Estados Unidos',
  'USA':                              'Estados Unidos',
  'Uruguay':                          'Uruguai',
  'Uzbekistan':                       'Uzbequistão',

  'Vanuatu':                          'Vanuatu',
  'Vatican City':                     'Vaticano',
  'Venezuela':                        'Venezuela',
  'Vietnam':                          'Vietnã',

  'Wales':                            'País de Gales',

  'Yemen':                            'Iêmen',

  'Zambia':                           'Zâmbia',
  'Zimbabwe':                         'Zimbábue',
}

export function getCountryName(englishName: string): string {
  return COUNTRY_NAMES[englishName] ?? englishName
}
