const TEAM_EMOJIS: Record<string, string> = {
  'América Mineiro':        '🇳🇬',
  'Athletic Club (MG)':    '🏁',
  'Atlético Goianiense':   '🇦🇴',
  'Atlético Mineiro':      '🇩🇪',
  'Athletico Paranaense':  '🇦🇴',
  'Avaí':                  '🇫🇮',
  'Bahia':                 '🇷🇺',
  'Botafogo':              '🔥',
  'Botafogo-SP':           '🇾🇪',
  'Ceará':                 '🏁',
  'Chapecoense':           '🇸🇦',
  'Corinthians':           '🏁',
  'Coritiba':              '🇳🇬',
  'CRB':                   '🇦🇹',
  'Criciúma':              '🇧🇪',
  'Cruzeiro':              '🇸🇴',
  'Cuiabá':                '🇳🇬',
  'Flamengo':              '🇦🇴',
  'Fluminense':            '🇭🇺',
  'Fortaleza':             '🇷🇺',
  'Goiás':                 '🇳🇬',
  'Grêmio':                '🇪🇪',
  'Internacional':         '🇦🇹',
  'Juventude':             '🇳🇬',
  'Londrina':              '🇫🇮',
  'Mirassol':              '🇯🇲',
  'Náutico':               '🇦🇹',
  'Novorizontino':         '🇧🇪',
  'Operário-PR':           '🏁',
  'Palmeiras':             '🇳🇬',
  'Ponte Preta':           '🏁',
  'Red Bull Bragantino':   '🇵🇱',
  'Remo':                  '🇫🇮',
  'Santos':                '🐳',
  'São Paulo':             '🇾🇪',
  'Sport Recife':          '🇦🇱',
  'Vasco da Gama':         '🏴‍☠️',
  'Vila Nova':             '🇦🇹',
  'Vitória':               '🇦🇴',
}

export function getTeamEmoji(teamName: string): string {
  return TEAM_EMOJIS[teamName] ?? '⚽'
}
